### This is a personal project to predict that a women is having breast cancer or not 

### In this we will Train a basic neural network 


In [ ]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer

In [ ]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv'
)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns= ['id','Unnamed: 32'], inplace = True)

In [ ]:
df.head(
)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [ ]:
df.shape

(569, 31)

### Train - Test - Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

### Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.80301637, -1.36795735, -0.77636681, ..., -0.43909723,
        -1.308572  , -0.88666074],
       [ 0.57390063, -0.30872885,  0.6234526 , ...,  1.10091685,
         2.16626175,  2.15647957],
       [ 0.16508403, -1.22877142,  0.26196982, ..., -0.05996723,
        -0.14655426,  0.44340996],
       ...,
       [ 0.87483506,  0.67972714,  0.81283993, ...,  1.28518416,
         0.47692836, -0.45537544],
       [-1.43838549, -0.06810233, -1.3087099 , ..., -0.00315148,
         0.34710293,  1.17977749],
       [ 0.13385499,  0.55233663,  0.22862118, ...,  2.38618136,
         2.15664505,  2.38693736]])

In [ ]:
y_train   # The values are in string format . we need to convert them into numerical format using label encoder for the neural network to understand it .

,diagnosis
139,B
34,M
421,B
368,M
304,B
...,...
36,M
168,M
264,M
318,B


### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(df.iloc[:,0])
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

### Numpy arrays to Pytorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.8030, -1.3680, -0.7764,  ..., -0.4391, -1.3086, -0.8867],
        [ 0.5739, -0.3087,  0.6235,  ...,  1.1009,  2.1663,  2.1565],
        [ 0.1651, -1.2288,  0.2620,  ..., -0.0600, -0.1466,  0.4434],
        ...,
        [ 0.8748,  0.6797,  0.8128,  ...,  1.2852,  0.4769, -0.4554],
        [-1.4384, -0.0681, -1.3087,  ..., -0.0032,  0.3471,  1.1798],
        [ 0.1339,  0.5523,  0.2286,  ...,  2.3862,  2.1566,  2.3869]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([569])

## Defining the Model

In [ ]:
class MysimpleNN():
    def __init__(self,input_size):
        self.weights = torch.rand(input_size,1,dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype= torch.float64,requires_grad = True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline


In [ ]:
# Create  Model
model = MysimpleNN(input_size = X_train_tensor.shape[1])
model.weights
# define loop
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    

    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():

        model.weights.data -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 3.7240403778505717
Epoch 2, Loss: 3.602168849546926
Epoch 3, Loss: 3.4717616575393264
Epoch 4, Loss: 3.3361471563382823
Epoch 5, Loss: 3.198975816255146
Epoch 6, Loss: 3.061109833897126
Epoch 7, Loss: 2.916472860858771
Epoch 8, Loss: 2.7688385525311072
Epoch 9, Loss: 2.616876439558876
Epoch 10, Loss: 2.4681413336655593
Epoch 11, Loss: 2.318305250165342
Epoch 12, Loss: 2.1619337099540625
Epoch 13, Loss: 2.008373634724132
Epoch 14, Loss: 1.855358665848174
Epoch 15, Loss: 1.7068073245162512
Epoch 16, Loss: 1.5654443648004615
Epoch 17, Loss: 1.4299098442750513
Epoch 18, Loss: 1.307513703608378
Epoch 19, Loss: 1.1994172356111041
Epoch 20, Loss: 1.1063948778971768
Epoch 21, Loss: 1.0285883426462583
Epoch 22, Loss: 0.9653326987874481
Epoch 23, Loss: 0.9151685859294569
Epoch 24, Loss: 0.8760689861699428
Epoch 25, Loss: 0.8457877473479456


In [ ]:
model.bias

tensor([-0.1291], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [ ]:
# evaluate the model on test data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred_labels = (y_pred > 0.9).float()
    accuracy = (y_pred_labels.squeeze() == y_test_tensor).float().mean()
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.6140350699424744


### Fast Api Backend

In [ ]:
import pickle
import os
# Save scaler
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# Save model weights — .detach() is the fix
torch.save({
    "weights": model.weights.detach(),
    "bias": model.bias.detach()
}, "model.pt")

# Check if scaler exists and has content
print("scaler.pkl size:", os.path.getsize("scaler.pkl"), "bytes")

print("✅ Saved successfully!")

scaler.pkl size: 1772 bytes
✅ Saved successfully!


In [ ]:
import sys
print("Notebook Python:", sys.version)

Notebook Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
import sys
print(sys.executable)


/usr/bin/python3


In [ ]:
import os
print(os.getcwd())

/content


In [ ]:
!pip install fastapi uvicorn pyngrok nest-asyncio


In [1]:
from pyngrok import ngrok

# Kill all existing tunnels first
ngrok.kill()

print("✅ Old tunnels closed!")

ModuleNotFoundError: No module named 'pyngrok'

In [ ]:
import pickle
import torch
import numpy as np
import json
import nest_asyncio
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok

# ── Setup ─────────────────────────────────────────
nest_asyncio.apply()

# Paste your ngrok token here
ngrok.set_auth_token("3ARrjyoYVHVx4clhmxADkg9FHun_7Y5xMLdxjH6a9YSzhfxKZ")

# ── Load model & scaler ───────────────────────────
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

model_data = torch.load("model.pt", weights_only=False)
weights = model_data["weights"]
bias    = model_data["bias"]

# ── FastAPI app ───────────────────────────────────
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"]
)

class InputData(BaseModel):
    features: list[float]

@app.get("/")
def root():
    return {"status": "✅ Breast Cancer NN API is running!"}

@app.post("/predict")
def predict(data: InputData):
    if len(data.features) != 30:
        return {"error": f"Expected 30 features, got {len(data.features)}"}

    x        = np.array(data.features).reshape(1, -1)
    x_scaled = scaler.transform(x)
    x_tensor = torch.from_numpy(x_scaled)

    with torch.no_grad():
        z    = torch.matmul(x_tensor, weights) + bias
        prob = torch.sigmoid(z).item()

    label      = "M" if prob > 0.5 else "B"
    confidence = round(max(prob, 1 - prob) * 100, 1)

    return {
        "prediction": label,
        "confidence": confidence,
        "probability": round(prob, 4),
        "reasoning": (
            f"The model assigned a malignancy probability of {round(prob*100,1)}%. "
            f"Features drove this {'above' if prob>0.5 else 'below'} the 0.5 decision threshold."
        )
    }

# ── Start ngrok tunnel ────────────────────────────
public_url = ngrok.connect(8000)
print(f"🌍 Public URL: {public_url}")
print(f"✅ Share this URL with the UI!")

# ── Start server ──────────────────────────────────

# ── Start server ──────────────────────────────────
import asyncio
config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)
await server.serve()

🌍 Public URL: NgrokTunnel: "https://germaine-wedgier-loan.ngrok-free.dev" -> "http://localhost:8000"
✅ Share this URL with the UI!


INFO:     Started server process [27631]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): [errno 98] address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/server.py", line 172, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1584, in create_server
    raise OSError(err.errno, msg) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): [errno 98] address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3551, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_27631/911883245.py", line 80, in <cell line: 1>
    await server.serve()
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/server.py", line 79, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/server.py", line 9

TypeError: object of type 'NoneType' has no len()