### This is a personal project to predict that a women is having breast cancer or not 

### In this we will Train a basic neural network 


In [6]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer

In [7]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv'
)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [8]:
df.shape

(569, 33)

In [9]:
df.drop(columns= ['id','Unnamed: 32'], inplace = True)

In [10]:
df.head(
)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [11]:
df.shape

(569, 31)

### Train - Test - Split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

### Scaling

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 1.36637571,  0.7827615 ,  1.39643551, ...,  0.84563237,
         0.47413851,  0.48873175],
       [ 1.26397934,  0.18480378,  1.1314425 , ...,  0.21820814,
        -0.53330546, -1.45792832],
       [ 0.20957347, -0.88008507,  0.1899143 , ...,  0.34702712,
         0.08950734,  0.00877165],
       ...,
       [-0.86143722,  0.77084999, -0.85239153, ..., -0.77097012,
         0.43551446, -0.17561349],
       [-0.62066737, -0.84673285, -0.63317004, ..., -0.58622854,
         0.77347489, -0.23595772],
       [ 1.34423595,  1.68803614,  1.46067624, ...,  1.04719619,
        -0.94529532,  0.47867438]], shape=(455, 30))

In [14]:
y_train   # The values are in string format . we need to convert them into numerical format using label encoder for the neural network to understand it .

198    M
277    M
227    B
472    B
164    M
      ..
361    B
82     M
551    B
84     B
83     M
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [15]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(df.iloc[:,0])
y_test = encoder.transform(y_test)

In [16]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

### Numpy arrays to Pytorch tensors

In [17]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor

tensor([[ 1.3664,  0.7828,  1.3964,  ...,  0.8456,  0.4741,  0.4887],
        [ 1.2640,  0.1848,  1.1314,  ...,  0.2182, -0.5333, -1.4579],
        [ 0.2096, -0.8801,  0.1899,  ...,  0.3470,  0.0895,  0.0088],
        ...,
        [-0.8614,  0.7708, -0.8524,  ..., -0.7710,  0.4355, -0.1756],
        [-0.6207, -0.8467, -0.6332,  ..., -0.5862,  0.7735, -0.2360],
        [ 1.3442,  1.6880,  1.4607,  ...,  1.0472, -0.9453,  0.4787]],
       dtype=torch.float64)

In [19]:
y_train_tensor.shape

torch.Size([569])

## Defining the Model

In [20]:
class MysimpleNN():
    def __init__(self,input_size):
        self.weights = torch.rand(input_size,1,dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype= torch.float64,requires_grad = True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameters

In [21]:
learning_rate = 0.1
epochs = 25

### Training Pipeline


In [22]:
# Create  Model
model = MysimpleNN(input_size = X_train_tensor.shape[1])
model.weights
# define loop
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    

    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():

        model.weights.data -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 3.3844918446267283
Epoch 2, Loss: 3.24146802368482
Epoch 3, Loss: 3.096455239161549
Epoch 4, Loss: 2.9456038091746293
Epoch 5, Loss: 2.789947355752449
Epoch 6, Loss: 2.623895014301845
Epoch 7, Loss: 2.4575670738463073
Epoch 8, Loss: 2.288930095306274
Epoch 9, Loss: 2.122390387958444
Epoch 10, Loss: 1.9584583537091802
Epoch 11, Loss: 1.7987889683795675
Epoch 12, Loss: 1.6408487785292105
Epoch 13, Loss: 1.4898279528844065
Epoch 14, Loss: 1.3521951663620606
Epoch 15, Loss: 1.2298027750548468
Epoch 16, Loss: 1.1242209833705628
Epoch 17, Loss: 1.0363853165576569
Epoch 18, Loss: 0.9661372866903528
Epoch 19, Loss: 0.9119031328594637
Epoch 20, Loss: 0.8709342214297302
Epoch 21, Loss: 0.8400898847811847
Epoch 22, Loss: 0.8165621596003181
Epoch 23, Loss: 0.7981827303345945
Epoch 24, Loss: 0.7834157618334947
Epoch 25, Loss: 0.7712258903129061


In [23]:
model.bias

tensor([-0.1608], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [24]:
# evaluate the model on test data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred_labels = (y_pred > 0.9).float()
    accuracy = (y_pred_labels.squeeze() == y_test_tensor).float().mean()
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.6578947305679321


### Fast Api Backend

In [25]:
import pickle
import os
# Save scaler
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# Save model weights — .detach() is the fix
torch.save({
    "weights": model.weights.detach(),
    "bias": model.bias.detach()
}, "model.pt")

# Check if scaler exists and has content
print("scaler.pkl size:", os.path.getsize("scaler.pkl"), "bytes")

print("✅ Saved successfully!")

scaler.pkl size: 1761 bytes
✅ Saved successfully!


In [26]:
import sys
print("Notebook Python:", sys.version)

Notebook Python: 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)]


In [27]:
import sys
print(sys.executable)


c:\Users\Harshu\Machine-Learning\myenv\Scripts\python.exe


In [28]:
import os
print(os.getcwd())

c:\Users\Harshu\Machine-Learning\Projects


In [29]:
!pip install fastapi uvicorn pyngrok nest-asyncio


  Using cached fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
  Using cached uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
  Using cached starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  Using cached pydantic_core-2.41.5-cp314-cp314-win_amd64.whl.metadata (7.4 kB)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Using cached fastapi-0.135.1-py3-none-any.whl (116 kB)
Using cached uvicorn-0.41.0-py3-none-any.whl (68 kB)
Using cached anno


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from pyngrok import ngrok

# Kill all existing tunnels first
ngrok.kill()

print("✅ Old tunnels closed!")

✅ Old tunnels closed!


In [31]:
import pickle
import torch
import numpy as np
import json
import nest_asyncio
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok

# ── Setup ─────────────────────────────────────────
nest_asyncio.apply()

# Paste your ngrok token here
ngrok.set_auth_token("3ARrjyoYVHVx4clhmxADkg9FHun_7Y5xMLdxjH6a9YSzhfxKZ")

# ── Load model & scaler ───────────────────────────
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

model_data = torch.load("model.pt", weights_only=False)
weights = model_data["weights"]
bias    = model_data["bias"]

# ── FastAPI app ───────────────────────────────────
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"]
)

class InputData(BaseModel):
    features: list[float]

@app.get("/")
def root():
    return {"status": "✅ Breast Cancer NN API is running!"}

@app.post("/predict")
def predict(data: InputData):
    if len(data.features) != 30:
        return {"error": f"Expected 30 features, got {len(data.features)}"}

    x        = np.array(data.features).reshape(1, -1)
    x_scaled = scaler.transform(x)
    x_tensor = torch.from_numpy(x_scaled)

    with torch.no_grad():
        z    = torch.matmul(x_tensor, weights) + bias
        prob = torch.sigmoid(z).item()

    label      = "M" if prob > 0.5 else "B"
    confidence = round(max(prob, 1 - prob) * 100, 1)

    return {
        "prediction": label,
        "confidence": confidence,
        "probability": round(prob, 4),
        "reasoning": (
            f"The model assigned a malignancy probability of {round(prob*100,1)}%. "
            f"Features drove this {'above' if prob>0.5 else 'below'} the 0.5 decision threshold."
        )
    }

# ── Start ngrok tunnel ────────────────────────────
public_url = ngrok.connect(8000)
print(f"🌍 Public URL: {public_url}")
print(f"✅ Share this URL with the UI!")

# ── Start server ──────────────────────────────────

# ── Start server ──────────────────────────────────
import asyncio
config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)
await server.serve()

INFO:     Started server process [28108]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


🌍 Public URL: NgrokTunnel: "https://germaine-wedgier-loan.ngrok-free.dev" -> "http://localhost:8000"
✅ Share this URL with the UI!
INFO:     103.124.13.100:0 - "GET / HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 410, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\fastapi\applications.py", line 1160, in __call__
    await super().__call__(scope, receive, send)
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\starlette\applications.py", line 107, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\Harshu\Machi

INFO:     103.124.13.100:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     103.124.13.100:0 - "GET / HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 410, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\fastapi\applications.py", line 1160, in __call__
    await super().__call__(scope, receive, send)
  File "c:\Users\Harshu\Machine-Learning\myenv\Lib\site-packages\starlette\applications.py", line 107, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\Harshu\Machi