In [2]:
import torch

In [3]:
print(torch.__version__)

2.10.0+cu128


In [4]:
#  This is a simple method to create a 1D Tensor from pytorch

x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


In [5]:
# Creating a multi dimensional Tensor in torch

y = torch.tensor([[1,2],[3,4]])
print(y)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Another way to create a tensor in zeros

z = torch.zeros(3,4)  # 3 belongs to rows and 4 belongs to columns
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
# A tensor filled with values of ones 1
x = torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# Another way to create tensor by rand function
r = torch.rand(3,5)  # So this function will create list of random decimal numbers 
r

tensor([[0.2505, 0.5719, 0.1483, 0.8433, 0.5414],
        [0.6261, 0.0857, 0.4982, 0.9873, 0.1397],
        [0.3935, 0.1953, 0.0057, 0.2415, 0.1524]])

## Creating Tensors in Pythorch
 

In [9]:
# Using Empty
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# Using Zeros 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Using rand
torch.rand(2,3)  # this rand keyword genrerates random numbers everytime it is being called so to solve this problem we use Manual Seed to fix the rand value to a fixed set of numbers


tensor([[0.5330, 0.0861, 0.6848],
        [0.3784, 0.2763, 0.9828]])

In [15]:
# Manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
# using tensor
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # We can make custom tensors of any type 1D , 2D , 3D

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [23]:
# Other ways 

# using arange
print("using arange:",torch.arange(0,10,2))

# using linspace
print("using linspace :",torch.linspace(0,10,10))

# using eye
print("using eye :",torch.eye(5))  # used for identity matrics

# using full 
print("using full :",torch.full((3,3),5))

using arange: tensor([0, 2, 4, 6, 8])
using linspace : tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye : tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full : tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor shape

In [27]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [30]:
torch.empty_like(x)  # This empty_like function makes another tensor with random values but the shape will be same as we have given in it


tensor([[              99998,                  36,                   0],
        [                  0,                   0, 7364060719469637682]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [41]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Datatype in pytorch 

In [34]:
# Find data type 
x.dtype

torch.int64

In [37]:
# Assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [38]:
# Using .to function

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Operation in Pytorch

In [43]:
# 1st . Scalar operations

y = torch.rand(2,2)
y

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [46]:
# Addition
print(y + 2)

# Subtraction
print(y - 2)

# Multiplication
print(y * 3)

# division
print(y / 3)

# int division
print((x * 100)//3)

# Mod
print(((x * 100)//3)%2) 

# Power
print(x ** 2) 

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])
tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])
tensor([[2.9907, 2.2695],
        [0.6717, 0.9070]])
tensor([[0.3323, 0.2522],
        [0.0746, 0.1008]])
tensor([[ 33,  66, 100],
        [133, 166, 200]])
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [47]:
# 2nd Element wise operations 

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [ ]:
# Addition
print(a + b)

# Subtraction
print(a + b)

# Multiplication
print(a + b)

# division

# Power

# Modulus
