In [3]:
import torch

In [4]:
print(torch.__version__)

2.10.0+cu128


In [5]:
#  This is a simple method to create a 1D Tensor from pytorch

x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


In [6]:
# Creating a multi dimensional Tensor in torch

y = torch.tensor([[1,2],[3,4]])
print(y)

tensor([[1, 2],
        [3, 4]])


In [7]:
# Another way to create a tensor in zeros

z = torch.zeros(3,4)  # 3 belongs to rows and 4 belongs to columns
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
# A tensor filled with values of ones 1
x = torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
# Another way to create tensor by rand function
r = torch.rand(3,5)  # So this function will create list of random decimal numbers 
r

tensor([[0.7993, 0.9370, 0.3976, 0.5323, 0.4442],
        [0.9211, 0.8417, 0.5710, 0.8857, 0.6552],
        [0.5043, 0.6351, 0.7871, 0.1492, 0.8272]])

## Creating Tensors in Pythorch
 

In [10]:
# Using Empty
torch.empty(2,3)

tensor([[1.7426e+14, 4.3876e-41, 2.2717e+01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [11]:
# Using Zeros 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Using rand
torch.rand(2,3)  # this rand keyword genrerates random numbers everytime it is being called so to solve this problem we use Manual Seed to fix the rand value to a fixed set of numbers


tensor([[0.5168, 0.6998, 0.0676],
        [0.1512, 0.2970, 0.2581]])

In [14]:
# Manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # We can make custom tensors of any type 1D , 2D , 3D

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [16]:
# Other ways 

# using arange
print("using arange:",torch.arange(0,10,2))

# using linspace
print("using linspace :",torch.linspace(0,10,10))

# using eye
print("using eye :",torch.eye(5))  # used for identity matrics

# using full 
print("using full :",torch.full((3,3),5))

using arange: tensor([0, 2, 4, 6, 8])
using linspace : tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye : tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full : tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor shape

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)  # This empty_like function makes another tensor with random values but the shape will be same as we have given in it


tensor([[134481182621072, 134481182621072,      1181335840],
        [              0,               0,      1181366496]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Datatype in pytorch 

In [22]:
# Find data type 
x.dtype

torch.int64

In [23]:
# Assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# Using .to function

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Operation in Pytorch

In [25]:
# 1st . Scalar operations

y = torch.rand(2,2)
y

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# Addition
print(y + 2)

# Subtraction
print(y - 2)

# Multiplication
print(y * 3)

# division
print(y / 3)

# int division
print((x * 100)//3)

# Mod
print(((x * 100)//3)%2) 

# Power
print(x ** 2) 

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[ 33,  66, 100],
        [133, 166, 200]])
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [27]:
# 2nd Element wise operations 

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [28]:
# Addition
print(a + b)

# Subtraction
print(a + b)

# Multiplication
print(a + b)

# division
print(a / b)

# Power
print(a ** b)

# Modulus
print(a % b)


tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


### Inplace Operations


In [29]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)


tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [30]:
m+n

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [31]:
m.add(n)  # This is another way to add two tensors together

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [32]:
m

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [33]:
n

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [34]:
torch.relu(m)   # Relu is a activation function which is used in deep learning to convert all the negative values to zero and keep the positive values as it is . This function will create a seperate tensor with the relu values but it will not change the original tensoer m  so if we want to change the original tensor m then we can use inplace operation by adding _ at the end of the function name 

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [35]:
m.relu_() # This _ function represents an in-place operation . This will change the original tensor m and convert all the negative values to zero and keep the positive values as it is . 

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [36]:
m

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

### Copying a Tensor



In [37]:
a = torch.rand(2,3)
a


tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [38]:
b = a # We are making a copy of a in b but it is not a deep copy it is a shallow copy because if we change the value of a then the value of b will also change because they are pointing to the same memory location 

In [39]:
a[0][0]= 0
a

tensor([[0.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [40]:
b


tensor([[0.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [41]:
# so to prevent this type of problem we can use the clone function to make a deep copy of the tensor 
b = a.clone()
a[0][0]= 1
a


tensor([[1.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [42]:
b

tensor([[0.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [43]:
id(a)

134475680539712

In [44]:
id(b)

134481132869648

### Tensor Operations on GPU

In [45]:
torch.cuda.is_available()  # This function is used to check if the cuda is available or not in our system . If it returns true then we can use the cuda to perform operations on GPU which will be faster than CPU . If it returns false then we can only use CPU for our operations .

True

In [46]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')  # This line of code is used to set the device to cuda if it is available otherwise it will set the device to cpu . This is a common practice in deep learning to make the code compatible with both CPU and GPU .
print(device)

cuda


In [47]:
# Creating new tensor on the device 
torch.rand(2,3).to(device)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]], device='cuda:0')

In [48]:
# Moving an existing tensor to the device
a

tensor([[1.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [49]:
b = a.to(device)
b

tensor([[1.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]], device='cuda:0')

In [50]:
# Comparision between CPU and Cuda Speed
import time


# Define the size of the tensor
size = 1000 # Large size for better comparison

# Create random matrices on CPU

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# Measure time on CPU
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)     # Matrix multiplication on cpu
cpu_time = time.time() - start_time_cpu
print(f"CPU Time: {cpu_time:.4f} seconds")

# Move Matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)     # Matrix multiplication on gpu
torch.cuda.synchronize()  # Wait for GPU to finish
gpu_time = time.time() - start_time_gpu

print(f"GPU Time: {gpu_time:.4f} seconds")

# compare the results
print(f"Results are close: {torch.allclose(result_cpu, result_gpu.cpu())}")



CPU Time: 0.0433 seconds
GPU Time: 0.1023 seconds
Results are close: True


### Reshaping Tensors


In [52]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [53]:
# Reshape a tensor
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [54]:
# Flatten 
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
b = torch.rand(2,3,4)
b

tensor([[[0.6628, 0.9300, 0.1961, 0.4935],
         [0.1812, 0.0087, 0.7314, 0.2809],
         [0.9137, 0.8614, 0.7215, 0.4557]],

        [[0.3662, 0.2905, 0.5844, 0.1153],
         [0.9050, 0.4301, 0.4167, 0.2939],
         [0.1320, 0.9595, 0.4003, 0.5078]]])

In [56]:
# Permutation
b.permute(2,0,1)

tensor([[[0.6628, 0.1812, 0.9137],
         [0.3662, 0.9050, 0.1320]],

        [[0.9300, 0.0087, 0.8614],
         [0.2905, 0.4301, 0.9595]],

        [[0.1961, 0.7314, 0.7215],
         [0.5844, 0.4167, 0.4003]],

        [[0.4935, 0.2809, 0.4557],
         [0.1153, 0.2939, 0.5078]]])

In [61]:
# Unsqueeze
c = torch.rand(226,226,3)    # This is a prfect example of the modern world image pixels

In [62]:
c.unsqueeze(0).shape # This will add a new dimension at the beginning of the tensor and change the shape from (226,226,30) to (1,226,226,3) which is useful when we want to add a batch dimension to our data before feeding it into a neural network 



torch.Size([1, 226, 226, 3])

In [63]:
# squeeze
d = torch.rand(1,20)
d.squeeze().shape  # This will remove the dimensions of size 1 from the tensor and change the shape from (1,20) to (20,) which is useful when we want to remove the batch dimension from our data after getting the output from a neural network

torch.Size([20])

# Numpy and Pytorch
 

In [64]:
import numpy as np 


In [65]:
a = torch.tensor([1,2,3,4,5])
a


tensor([1, 2, 3, 4, 5])

In [66]:
b = a.numpy()

In [67]:
b

array([1, 2, 3, 4, 5])

In [70]:
type(b)

numpy.ndarray

In [71]:
c = np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [72]:
torch.from_numpy(c)

tensor([1, 2, 3, 4, 5])