In [2]:
import torch

In [3]:
print(torch.__version__)

2.10.0+cu128


In [4]:
#  This is a simple method to create a 1D Tensor from pytorch

x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


In [5]:
# Creating a multi dimensional Tensor in torch

y = torch.tensor([[1,2],[3,4]])
print(y)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Another way to create a tensor in zeros

z = torch.zeros(3,4)  # 3 belongs to rows and 4 belongs to columns
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
# A tensor filled with values of ones 1
x = torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# Another way to create tensor by rand function
r = torch.rand(3,5)  # So this function will create list of random decimal numbers 
r

tensor([[0.0728, 0.7000, 0.5162, 0.1562, 0.5198],
        [0.9126, 0.7243, 0.0890, 0.5773, 0.2875],
        [0.5668, 0.5048, 0.7174, 0.8136, 0.6168]])

## Creating Tensors in Pythorch
 

In [9]:
# Using Empty
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# Using Zeros 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# Using rand
torch.rand(2,3)  # this rand keyword genrerates random numbers everytime it is being called so to solve this problem we use Manual Seed to fix the rand value to a fixed set of numbers


tensor([[0.2506, 0.8455, 0.6656],
        [0.1565, 0.4767, 0.4619]])

In [13]:
# Manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # We can make custom tensors of any type 1D , 2D , 3D

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [15]:
# Other ways 

# using arange
print("using arange:",torch.arange(0,10,2))

# using linspace
print("using linspace :",torch.linspace(0,10,10))

# using eye
print("using eye :",torch.eye(5))  # used for identity matrics

# using full 
print("using full :",torch.full((3,3),5))

using arange: tensor([0, 2, 4, 6, 8])
using linspace : tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye : tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full : tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor shape

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)  # This empty_like function makes another tensor with random values but the shape will be same as we have given in it


tensor([[138161443089808,       546666448,       538142816],
        [      546549216,               0,       546666464]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Datatype in pytorch 

In [21]:
# Find data type 
x.dtype

torch.int64

In [22]:
# Assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
# Using .to function

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Operation in Pytorch

In [24]:
# 1st . Scalar operations

y = torch.rand(2,2)
y

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [25]:
# Addition
print(y + 2)

# Subtraction
print(y - 2)

# Multiplication
print(y * 3)

# division
print(y / 3)

# int division
print((x * 100)//3)

# Mod
print(((x * 100)//3)%2) 

# Power
print(x ** 2) 

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[ 33,  66, 100],
        [133, 166, 200]])
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [26]:
# 2nd Element wise operations 

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [27]:
# Addition
print(a + b)

# Subtraction
print(a + b)

# Multiplication
print(a + b)

# division
print(a / b)

# Power
print(a ** b)

# Modulus
print(a % b)


tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


### Inplace Operations


In [28]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)


tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [29]:
m+n

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [30]:
m.add(n)  # This is another way to add two tensors together

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [31]:
m

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [32]:
n

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [33]:
torch.relu(m)   # Relu is a activation function which is used in deep learning to convert all the negative values to zero and keep the positive values as it is . This function will create a seperate tensor with the relu values but it will not change the original tensoer m  so if we want to change the original tensor m then we can use inplace operation by adding _ at the end of the function name 

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [36]:
m.relu_() # This _ function represents an in-place operation . This will change the original tensor m and convert all the negative values to zero and keep the positive values as it is . 

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [37]:
m

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

### Copying a Tensor



In [38]:
a = torch.rand(2,3)
a


tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [39]:
b = a # We are making a copy of a in b but it is not a deep copy it is a shallow copy because if we change the value of a then the value of b will also change because they are pointing to the same memory location 

In [42]:
a[0][0]= 0
a

tensor([[0.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [41]:
b


tensor([[0.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [48]:
# so to prevent this type of problem we can use the clone function to make a deep copy of the tensor 
b = a.clone()
a[0][0]= 1
a


tensor([[1.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [49]:
b

tensor([[1.0000, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])