In [4]:
import torch

In [5]:
print(torch.__version__)

2.9.0+cu128


In [ ]:
#  This is a simple method to create a 1D Tensor from pytorch

x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


In [7]:
# Creating a multi dimensional Tensor in torch

y = torch.tensor([[1,2],[3,4]])
print(y)

tensor([[1, 2],
        [3, 4]])


In [11]:
# Another way to create a tensor in zeros

z = torch.zeros(3,4)  # 3 belongs to rows and 4 belongs to columns
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# A tensor filled with values of ones 1
x = torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])