In [11]:
# Importing tensorflow

import tensorflow as tf

In [14]:
# Creating Tensors : You can create tensors using TensorFlow’s tf.Tensor() or its various helper functions, such as tf.constant(), tf.Variable() or tf.zeros():

scalar_tensor = tf.constant(5)
vector_tensor = tf.constant([1, 2, 3, 4])

matrix_tensor = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
zeros_tensor = tf.zeros([3, 3])
ones_tensor = tf.ones([2, 2])

print(scalar_tensor,vector_tensor,matrix_tensor,tensor_3d,zeros_tensor,ones_tensor)

tf.Tensor(5, shape=(), dtype=int32) tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [16]:
# Teansor Operation : TensorFlow supports various operations that can be performed on tensors, such as element-wise operations, matrix multiplication, reshaping and more.

matrix_tensor = tf.constant([[1, 2], [3, 4]])

ones_tensor = tf.ones_like(matrix_tensor)
tensor_add = tf.add(matrix_tensor, ones_tensor)
matrix_mult = tf.matmul(matrix_tensor, matrix_tensor)
reshaped_tensor = tf.reshape(matrix_tensor, [4, 1])

transpose_tensor = tf.transpose(matrix_tensor)

print(matrix_tensor,ones_tensor,tensor_add,matrix_mult,reshaped_tensor,transpose_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32) tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32) tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [18]:
# Accessing Elements in Tensor : You can access specific elements within a tensor using indices. Similar to how you access elements in Python lists or NumPy arrays, TensorFlow provides slicing and indexing operations.

vector_tensor = tf.constant([1, 2, 3, 4])
first_element = vector_tensor[0]
matrix_tensor = tf.constant([[1, 2], [3, 4]])

matrix_slice = matrix_tensor[:2, :]

print(vector_tensor,first_element,matrix_tensor,matrix_slice)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

X_train = tf.random.normal([100, 10])
y_train = tf.random.normal([100, 1])

model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

model.fit(X_train, y_train, epochs=10)

Epoch 1/10


c:\ML_Scikit\deeplearning\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2075  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1159 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0609 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0403 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0114 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9876 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9648 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9387 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9214 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9059 
